### ISSUE TITLE
[FEAT] TODO 깨부시기 

### ISSUE THREAD

**Issue by C7C4FF** [boostcampaitech6/level2-3-nlp-finalproject-nlp-02#19]
## Background

제대로 작동하는 페이지를 만들기 위함.
서버에 올려서도 제대로 작동되도록 하기.

## To do 

- [x] app.py
     - [x] #21
- [x] lobby.py
     - [ ] request.get(url=current_user) 접속한 유저 정보 받아오기
     - [ ] st.cache 로... 처리할 수 있을까?
     - [x] st.session_state로 처리할 수 있을까..?
- [x] #20
     - [ ] 옆의 이미지 확장 버튼 숨기기
     - [ ] 녹음 로직 3번 반복
     - [ ] 자동으로 녹음 실행 (optional)
- [x] feedback.py
     - [x] 유저의 결과 목록에서 특정 날짜를 골라 query 보내기 - main.py, database/repository.py
     - [x] 해당 시험의 날짜를 받아오도록 함수 변경 - main.py
     - [x] #31
- [x] history.py
     - [x] request.get(url=result) 접속한 유저 정보 받아오기
