### ISSUE TITLE
[FEAT] DB 연결 관련 TODO

### ISSUE THREAD

**Issue by valofosho** [boostcampaitech6/level2-3-nlp-finalproject-nlp-02#28]
## Background

모델 output + question 등 DB 연결 사항들 처리
## To do 

- [x] tests 테이블 내 column 타입 fix
- [x] tests 테이블 백엔드 모델 추론 값 연결
- [x]  app.post('/test') app.post('/save') 엔드포인트 합치기

- [x] questions 테이블 내 질문 적재
- [x] questions 테이블 백엔드 연결 확인
- [x] q_id tests 테이블과 연결하는 방법 찾기
